name: Auto-approve Copilot CI

on:
  # Only watch the CI workflow you want to auto-approve.
  # You can reference by workflow *name* or by file name.
  workflow_run:
    workflows: ["CI"]
    types: [requested]

permissions:
  actions: write
  contents: read

jobs:
  approve:
    # Approve only runs that:
    #  - were triggered by a PR from a fork,
    #  - and the actor is Copilot's bot/app user.
    # Print the actor/login from one run if you're unsure of the exact value.
    if: >
      github.event.workflow_run.event == 'pull_request' &&
      github.event.workflow_run.pull_requests[0].base.ref == 'main' &&
      github.event.workflow_run.head_repository.fork == true &&
      (
        github.event.workflow_run.actor.login == 'github-copilot' ||
        github.event.workflow_run.actor.login == 'github-copilot[bot]' ||
        github.event.workflow_run.actor.login == 'copilot-changes[bot]'
      )
    runs-on: ubuntu-latest
    steps:
      - name: Approve the queued run
        env:
          RUN_ID: ${{ github.event.workflow_run.id }}
          REPO:   ${{ github.repository }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Approve the blocked run
          gh api -X POST repos/$REPO/actions/runs/$RUN_ID/approve